Move HTML into Twig templates
justin-mueller/flugplanung pull request #20
Opened 2024-03-01 12:07 UTC by kdambekalns

This adds Twig to the project and moves markup into template files.

- no more mixing between HTML markup and PHP
- moves tab (module) display logic to the server side

The added `typeof` checks in the JS are a workaround - the JS for a module should only be loaded when the module is active.

2024-03-01 12:08 UTC, kdambekalns commented
Ich hoffe das ist ok, aber ich habe seit Jahren keinen Mix aus HTML und PHP mehr "aktiv betrieben". Auf Dauer sind wir so flexibler, übersichtlicher und sicherer unterwegs, IMHO…

2024-03-05 10:06 UTC, justin-mueller commented
Ich kümmere mich drum sobald alles erstmal läuft! 👍

2024-03-06 16:56 UTC, justin-mueller commented
Kannst du vielleicht einen Branch dafür anlegen? Am besten vom jetztigen main ausgehend. Es kann sein dass zu viele Konflikte vorliegen

2024-03-07 14:26 UTC, justin-mueller approved these changes

2024-03-07 14:29 UTC, justin-mueller approved these changes
lets try...

2024-03-07 14:34 UTC, justin-mueller requested changes
Ich habs getestet, wird ein Fehler ausgegeben.
Muss diese Datei vielleicht noch hinzugefügt werden?

Warning: require_once(E:\Meine Ablage\synched_folders\htdocs\flugplanung/vendor/autoload.php): Failed to open stream: No such file or directory in E:\Meine Ablage\synched_folders\htdocs\flugplanung\index.php on line 6

2024-03-07 15:58 UTC, kdambekalns commented
> Ich habs getestet, wird ein Fehler ausgegeben. Muss diese Datei vielleicht noch hinzugefügt werden?
> 
> Warning: require_once(E:\Meine Ablage\synched_folders\htdocs\flugplanung/vendor/autoload.php): Failed to open stream: No such file or directory in E:\Meine Ablage\synched_folders\htdocs\flugplanung\index.php on line 6

Hast du denn `composer install` aufgerufen ([wie im README ergänzt](https://github.com/justin-mueller/flugplanung/pull/20/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5))?

[Composer](https://getcomposer.org/) holt damit die Dependencies, die nötig sind.

2024-04-04 18:11 UTC, merged